---
- name: Install Debian packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - make
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3

- name: Checking installed version of nodejs
  shell: /usr/bin/test "$({{nodejs_path}}bin/node -v 2> /dev/null)" = {{nodejs_version_tag}}
  register: required_version_installed
  ignore_errors: True
  changed_when: "required_version_installed.rc == 1"
  tags : check

- name: Download nodejs {{nodejs_version_tag}}
  get_url: url={{nodejs_tarball_url}} dest={{nodejs_tmp_dir}}{{nodejs_file_name}}
  when: required_version_installed.rc == 1

- name: Verify SHASUM of nodejs {{nodejs_version_tag}}
  shell: curl {{nodejs_shasum_url}} | grep {{nodejs_file_name}} | sha1sum -c chdir={{nodejs_tmp_dir}}
  when: required_version_installed.rc == 1

- name: Unpack nodejs {{nodejs_version_tag}}
  command: tar -xvzf {{nodejs_file_name}} chdir={{nodejs_tmp_dir}}
  when: required_version_installed.rc == 1

- name: Compile and install nodejs {{nodejs_version_tag}}
  shell: ./configure --prefix={{nodejs_path}} && make && make install chdir={{nodejs_tmp_dir}}{{nodejs_file_tag}}
  sudo: true
  when: required_version_installed.rc == 1

- name: NPM Install global packages
  npm: name={{item}} global=yes
  with_items: nodejs_global_packages
